coverage:
  range: 70..95
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
parsers:
  gcov:
    branch_detection:
      conditional: no
      loop: no
ignore:
  - "tests"
  - "benchmark"
  - "include/poolstl/internal/task_thread_pool.hpp"
